name: dio_logging_interceptor
description: Logging interceptor for DIO
version: 1.1.0
repository: https://github.com/granoeste/dio_logging_interceptor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.1
